let toggle=document.querySelector('.circle')
let togglebutton=document.querySelector('.toggle')
let card=document.querySelectorAll('.block')
let follower=document.querySelector('.followers')
let cardsection=document.querySelectorAll('.cardsection1')
let count=document.querySelectorAll('.count')
let likes=document.querySelectorAll('.likes')
let headingOverview=document.querySelector('.detail')
let socialHeading=document.querySelector('.social')
let wrapper=document.querySelector('.wrapper')
let bodyContent=document.querySelector('body')
let heading=document.querySelector('.headsection')

toggle.addEventListener('click',()=>{
    bodyContent.classList.toggle('wl3')
    wrapper.classList.toggle('wl2')
    socialHeading.classList.toggle('bl4')
    socialHeading.classList.toggle('wl')
    togglebutton.classList.toggle('move')
    togglebutton.classList.toggle('bg')
    follower.classList.toggle('white')
    follower.classList.toggle('cur1')
    card.forEach(el=>{
        el.classList.toggle('black')
        el.classList.toggle('black1')
    })
    headingOverview.classList.toggle('bl3')
    cardsection.forEach(card=>{
        card.classList.toggle('whbg')
        card.classList.toggle('cur')
    })
    likes.forEach(like=>{
        like.classList.toggle('bl1')
    })
    count.forEach(c=>{
        c.classList.toggle('bl')
    })
    heading.classList.toggle('bl5')
})